# Generated by Django 5.2.1 on 2025-05-29 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alunoturma'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.turma'),
        ),
        migrations.DeleteModel(
            name='AlunoTurma',
        ),
    ]
